### ISSUE TITLE
Make the device Windows only

### ISSUE THREAD

**Issue by ThomasParchmann** [n00b69/woa-beryllium#4]
### Question

Hey, first, this project is pretty awesome! 
I wanted to ask, if it is possible to delete the android phone partitions and use this as a windows only device to have more internal space available. Thanks for any help!

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Possible, but not recommended due to problematic charging in Windows.

It's recommended to keep around 3-4GB for Android just to charge.

If you really want to remove Android, use the partition instructions in the [Xiaomi Mi 8 Pro guide](https://github.com/n00b69/woa-equuleus/blob/main/guide/1-partition.md) guide, but skip the "recreating userdata" section. You also do not need to push parted, instead, run `adb shell parted /dev/block/sda`

**Comment by ThomasParchmann** [comment]
Thanks, this is already all i needed to know!

**Comment by ThomasParchmann** [comment]
Thanks for the fast answer, that is already all i needed to know!

**Comment by Kumar-Jy** [comment]
`adb shell winpartition winmax` tested and working perfectly for maximum windows partition
(this command will creat only 100mb userdata partition just for safety)
